### ISSUE TITLE
83.3 KBPS 

### ISSUE THREAD

**Issue by W203cnb** [latonita/arduino-canbus-monitor#14]
Hi.I have 2000 year mercedes.There are 2 can line.It works with canhacker which is 500 kbps but It doesn't work at all which is 83.3 kpbs

**Comment by latonita** [comment]
Hi. So whats the question? :)
Car works only with one speed. In your case it is 500kbps.
So you need to change 'arduino-canbus-monitor.ino' file, compile and upload to your arduino.
Line 33
Change 
`Can232::init(CAN_125KBPS, MCP_16MHz); `
to 
`Can232::init(CAN_500KBPS, MCP_16MHz); `

**Comment by latonita** [comment]
I don't know what the issue is. Check your connection, especially ground connection.
- Check your car is running - it might happen this CAN bus is only used when ignition is on.
- Without any of your arduinos connected - please check with oscilloscope or at least with multimeter that there is any data got published on this bus
- Another case - are you sure that 83.3 CAN line is alive? Can it be 'OBD-style-dialog' when you have to send request and get response? 
- In some cases it worked for me to only connect to CAN H, when ground is connected.

**Comment by Rapides06** [comment]
yes, the line is alive and the rx lamp of the can bus shield is on. How should we write the baudrate for 83.3 in can hacker?

**Comment by latonita** [comment]
oh, okay, now i got it :)
unfortunatlely, canhacker doesnt support 83.3 speed, so what you need is 
- either make 83.3 speed to be default
- or change one of S1-S8 commands to set up 83.3 speed. for example S2 50kbit. for this open `can-232.h` and change lines 154-155
```
const INT8U lw232CanBaudRates[] //PROGMEM
= { CAN_10KBPS, CAN_20KBPS, CAN_50KBPS, CAN_100KBPS, CAN_125KBPS, CAN_250KBPS, CAN_500KBPS, CAN_500KBPS /*CAN_800KBPS*/, CAN_1000KBPS, CAN_83K3BPS };
```
to 
```
const INT8U lw232CanBaudRates[] //PROGMEM
= { CAN_10KBPS, CAN_20KBPS, CAN_83K3BPS, CAN_100KBPS, CAN_125KBPS, CAN_250KBPS, CAN_500KBPS, CAN_500KBPS /*CAN_800KBPS*/, CAN_1000KBPS, CAN_83K3BPS };
```
Notice I replaced third option from 50 to 83

Then you can change speed in canhacker to 50kbps, but actually it will be 83.3

**Comment by Rapides06** [comment]
Ok.Very thanks

**Comment by Rapides06** [comment]
Hi,I made the change you said. But this time it reads a few data and the card fails. Rx and Tx lamps are constantly on.
